### ISSUE TITLE
Spreedly Credit Card Payment failed.

### ISSUE THREAD

**Issue by Jaydip2711** [spreedly/spreedly-ios#18]
Error Domain=com.spreedly.lib Code=60 "(null)" UserInfo={SpreedlyError=Direct API access has been disabled for this environment – payment methods can only be submitted from Spreedly Express or the iFrame payment form. If this is incorrect, the setting can be changed in your environment settings at https://id.spreedly.com.}

**Comment by davidsantoso** [comment]
@Jaydip2711 you'll need to update the settings on the Spreedly environment in which you would like to vault those cards. In your Spreedly account, go to Environments > Configure (for the specific environment) > Edit settings.

Then change the following setting on that environment to allow cards from more than the iFrame or Express products:

 
<img width="1167" alt="Screen Shot 2019-05-16 at 8 13 06 AM" src="https://user-images.githubusercontent.com/1288700/57853090-d7ce0d00-77b2-11e9-814d-e92f286f4d79.png">
