### ISSUE TITLE
Regarding response

### ISSUE THREAD

**Issue by pradeepkumari** [spreedly/spreedly-ios#5]
I didn't have lastname field in my UI. In creditcard class i removed lastname, but it shows error SpreedlyError=Last name can't be blank. How can i proceed? Anyhelp appreciated

**Comment by davidsantoso** [comment]
@pradeepkumari at the moment last name is a required field when using the Spreedly iOS SDK. Our direct API has support for skipping names however that feature has not made it's way to this library yet.

**Comment by pradeepkumari** [comment]
Please provide me direct API with skipping last name field.

**Comment by davidsantoso** [comment]
@pradeepkumari you can find the fields to skip name validation against our direct API here-

https://docs.spreedly.com/reference/api/v1/#create-credit-card
