### ISSUE TITLE
Direct API Details

### ISSUE THREAD

**Issue by raghubb4444** [spreedly/spreedly-ios#6]
As i didn't have last name field in my app, I want to use direct API. I am having your direct API. In that, I am not able to get Whole Url. What is the whole Url?

Request Format in Json:
{
  "payment_method": {
    "credit_card": {
      "first_name": "test",
      "last_name": "",
      "number": "4111111111111111",
      "verification_value": 123,
      "month": "3",
      "year": "2018"
    },
    "email": ""
  }
}

Authorization: Basic QWxhZGRpbjpvcGVuIHNlc2FtZQ==
Content-Type: application/json

1. Where should i give my environment Key?
2. what is the whole Url i should hit?

**Comment by raghubb4444** [comment]
http://imgh.us/Screen_Shot_2017-03-28_at_11.09.17_AM.png

**Comment by davidsantoso** [comment]
@raghubb4444 

> Where should i give my environment Key?

The direct API uses HTTP Basic Auth so your environment key will be your username and your access secret the password. See our credentials guide for more details. https://docs.spreedly.com/basics/credentials/

> what is the whole Url i should hit?

To create a payment method, you'll want to use `https://core.spreedly.com/v1/payment_methods.json`. https://docs.spreedly.com/reference/api/v1/#payment-methods

Hope this helps. For future inquiries please contact Spreedly support at https://support.spreedly.com/hc/en-us.

**Comment by raghubb4444** [comment]
http://imgh.us/Screen_Shot_2017-03-28_at_8.41.43_PM.png

**Comment by raghubb4444** [comment]
Getting Same Issue. If i send empty last name means, am not getting same response.

**Comment by rwdaigle** [comment]
Hi @raghubb4444, you will need to use the `allow_blank_name` property in the request to disable name validation.

```json
{
  "payment_method": {
    "credit_card": {
      "first_name": "Joe",
      "last_name": "",
      "number": "5555555555554444",
      "verification_value": 423,
      "month": "3",
      "year": "2032"
    },
    "email": "joey@example.com",
    "allow_blank_name": true
  }
}
```

You will need to contact Spreedly support at https://support.spreedly.com/hc/en-us if you have any further questions. Thank you!

**Comment by raghubb4444** [comment]
Thank you @rwdaigle ... Now I am getting token. How to do check test transaction with test login? I am having test login. Now i am having valid token. Where to send these token to check the transaction? Is there any Token for test user?

**Comment by rwdaigle** [comment]
@raghubb4444 You will need to contact Spreedly support at https://support.spreedly.com/hc/en-us if you have any further questions. Thank you!

**Comment by raghubb4444** [comment]
I sent mail. I am having small doubt. Please help out.                                                                                                https://pastebin.com/k5LBkd2J
