### ISSUE TITLE
Swift 3.0? 

### ISSUE THREAD

**Issue by psirigiano** [spreedly/spreedly-ios#7]
Is there plans to update this SDK, the newest Xcode version is forcing to update the Swift version and this pod fails after conversion.

**Comment by davidsantoso** [comment]
@psirigiano yes there are plans to update. I'm looking into this now.

**Comment by davidsantoso** [comment]
@psirigiano SDK is now Swift 3 supported. https://cocoapods.org/pods/Spreedly.
