### ISSUE TITLE
Retain Credit Card

### ISSUE THREAD

**Issue by speciosus** [spreedly/spreedly-ios#8]
Hi everyone
I'm developing a project with Spreedly's iOs SDK (pod 0.2.0) and I called the API in this manner:

~~~swift
let creditCard = ...
let client = SpreedlyAPIClient(environmentKey: "MY_KEY")                
client.createPaymentMethodTokenWithCreditCard(creditCard) { (payMethod, error) in
	...
}
~~~

In this scenario I'm able to save the card and use it but it's not retained. So I can use only once and, after that, I receive the following error:

~~~json
{
...
"message": "After a payment method has been successfully used, it must be retained before it is used again."
...
}
~~~

How can I retain a card? Is there any option?
Thanks in advance for the help

**Comment by davidsantoso** [comment]
Hi @speciosus - we don't actually allow cards to be automatically retained when using the iOS SDK (as well with iFrame and Express) for security reasons so once you have the token and have submitted it to your backend, you'll need to make an additional request to retain it.

See our [iOS guide](https://docs.spreedly.com/guides/mobile/ios/#using-a-custom-credit-card-form) and [retain API reference](https://docs.spreedly.com/reference/api/v1/#retain34) for more details.
